scalar Unknown
scalar DateTime
scalar Address
scalar AttachmentRef
scalar Amount_Tokens
scalar EthereumAddress
scalar EmailAddress
scalar Amount_Percentage
scalar Date
scalar URL
scalar Amount_Money
scalar OLabel
scalar Currency
scalar PHID
scalar OID
scalar Amount_Fiat
scalar Amount_Currency
scalar Amount_Crypto
scalar Amount
scalar Upload

type ExpenseReportState {
  lineItems: [LineItem!]!
}

type LineItem {
  id: String!
  amount: Float!
  currency: String!
  category: String!
  date: String!
}

# line-items

input AddLineItemInput {
  id: String!
  amount: Float!
  currency: String!
  category: String!
  date: String!
}

input UpdateLineItemInput {
  id: String!
  amount: Float
  currency: String
  category: String
  date: String
}

input DeleteLineItemInput {
  id: String!
}